version: '3.8'

services:
  go:
    container_name: go
    build:
      context: ./
    depends_on:
      - pg
    volumes:
      - ./:/app
      - .env:/app/.env
    ports:
      - ${APP_PORT}:${APP_PORT}

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - './docker/nginx/conf.d/default.conf.template:/etc/nginx/conf.d/default.conf.template'
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - APP_PORT=${APP_PORT}
    ports:
      - ${SERVER_PORT}:80
    depends_on:
      - pg
    command: /bin/sh -c "envsubst '$$SERVER_PORT $$APP_PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  pg:
    image: postgres:16.0-alpine
    container_name: enrichment_pg
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'

networks:
  default: